//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 07:32:06 PM EET 
//


package netconvert;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the netconvert package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OsmNodeTag_QNAME = new QName("", "tag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: netconvert
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Osm }
     * 
     */
    public Osm createOsm() {
        return new Osm();
    }

    /**
     * Create an instance of {@link Osm.Bounds }
     * 
     */
    public Osm.Bounds createOsmBounds() {
        return new Osm.Bounds();
    }

    /**
     * Create an instance of {@link Osm.XMLNode }
     * 
     */
    public Osm.XMLNode createOsmNode() {
        return new Osm.XMLNode();
    }

    /**
     * Create an instance of {@link Osm.Node.Tag }
     * 
     */
    public Osm.XMLNode.Tag createOsmNodeTag() {
        return new Osm.XMLNode.Tag();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Osm.Node.Tag }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tag", scope = Osm.XMLNode.class)
    public JAXBElement<Osm.XMLNode.Tag> createOsmNodeTag(Osm.XMLNode.Tag value) {
        return new JAXBElement<Osm.XMLNode.Tag>(_OsmNodeTag_QNAME, Osm.XMLNode.Tag.class, Osm.XMLNode.class, value);
    }

    /**
     * Create an instance of {@link Osm.XMLWay }
     * 
     */
    public Osm.XMLWay createOsmWay() {
        return new Osm.XMLWay();
    }

    /**
     * Create an instance of {@link Osm.Way.Nd }
     * 
     */
    public Osm.XMLWay.Nd createOsmWayNd() {
        return new Osm.XMLWay.Nd();
    }

    /**
     * Create an instance of {@link Osm.Way.Tag }
     * 
     */
    public Osm.XMLWay.Tag createOsmWayTag() {
        return new Osm.XMLWay.Tag();
    }

}
