//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 07:32:06 PM EET 
//


package netconvert;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bounds">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="minlat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="minlon" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="maxlat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="maxlon" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="node" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="changeset" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="way" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nd" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="changeset" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="generator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="attribution" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="license" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bounds",
    "node",
    "way"
})
@XmlRootElement(name = "osm")
public class Osm {

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="minlat" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="minlon" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="maxlat" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="maxlon" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Bounds {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "minlat")
        protected Float minlat;
        @XmlAttribute(name = "minlon")
        protected Float minlon;
        @XmlAttribute(name = "maxlat")
        protected Float maxlat;
        @XmlAttribute(name = "maxlon")
        protected Float maxlon;

        /**
         * Gets the value of the maxlat property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMaxlat() {
            return maxlat;
        }

        /**
         * Gets the value of the maxlon property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMaxlon() {
            return maxlon;
        }

        /**
         * Gets the value of the minlat property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMinlat() {
            return minlat;
        }

        /**
         * Gets the value of the minlon property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMinlon() {
            return minlon;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the maxlat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMaxlat(Float value) {
            this.maxlat = value;
        }

        /**
         * Sets the value of the maxlon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMaxlon(Float value) {
            this.maxlon = value;
        }

        /**
         * Sets the value of the minlat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMinlat(Float value) {
            this.minlat = value;
        }

        /**
         * Sets the value of the minlon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMinlon(Float value) {
            this.minlon = value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="changeset" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class XMLNode {

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Tag {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "k")
            protected String k;
            @XmlAttribute(name = "v")
            protected String v;

            /**
             * Gets the value of the k property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getK() {
                return k;
            }

            /**
             * Gets the value of the v property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getV() {
                return v;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the k property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setK(String value) {
                this.k = value;
            }

            /**
             * Sets the value of the v property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setV(String value) {
                this.v = value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }
        @XmlElementRef(name = "tag", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;
        @XmlAttribute(name = "id")
        protected Long id;
        @XmlAttribute(name = "visible")
        protected String visible;
        @XmlAttribute(name = "version")
        protected Byte version;
        @XmlAttribute(name = "changeset")
        protected Integer changeset;
        @XmlAttribute(name = "timestamp")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timestamp;
        @XmlAttribute(name = "user")
        protected String user;
        @XmlAttribute(name = "uid")
        protected Integer uid;
        @XmlAttribute(name = "lat")
        protected Float lat;
        
        
        
        @XmlAttribute(name = "lon")
        protected Float lon;

        /**
         * Gets the value of the changeset property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getChangeset() {
            return changeset;
        }

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Osm.Node.Tag }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getId() {
            return id;
        }

        /**
         * Gets the value of the lat property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getLat() {
            return lat;
        }

        /**
         * Gets the value of the lon property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getLon() {
            return lon;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimestamp() {
            return timestamp;
        }

        /**
         * Gets the value of the uid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUid() {
            return uid;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUser() {
            return user;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getVersion() {
            return version;
        }

        /**
         * Gets the value of the visible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisible() {
            return visible;
        }

        /**
         * Sets the value of the changeset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setChangeset(Integer value) {
            this.changeset = value;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setId(Long value) {
            this.id = value;
        }

        /**
         * Sets the value of the lat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLat(Float value) {
            this.lat = value;
        }

        /**
         * Sets the value of the lon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLon(Float value) {
            this.lon = value;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimestamp(XMLGregorianCalendar value) {
            this.timestamp = value;
        }

        /**
         * Sets the value of the uid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUid(Integer value) {
            this.uid = value;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUser(String value) {
            this.user = value;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setVersion(Byte value) {
            this.version = value;
        }



        
        /**
         * Sets the value of the visible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisible(String value) {
            this.visible = value;
        }

    }
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nd" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="changeset" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nd",
        "tag"
    })
    public static class XMLWay {

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Nd {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "ref")
            protected Long ref;

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getRef() {
                return ref;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setRef(Long value) {
                this.ref = value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }
        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Tag {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "k")
            protected String k;
            @XmlAttribute(name = "v")
            protected String v;

            /**
             * Gets the value of the k property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getK() {
                return k;
            }

            /**
             * Gets the value of the v property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getV() {
                return v;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the k property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setK(String value) {
                this.k = value;
            }

            /**
             * Sets the value of the v property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setV(String value) {
                this.v = value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }
        protected List<Osm.XMLWay.Nd> nd;
        protected List<Osm.XMLWay.Tag> tag;
        @XmlAttribute(name = "id")
        protected Integer id;
        @XmlAttribute(name = "visible")
        protected String visible;
        @XmlAttribute(name = "version")
        protected Byte version;
        @XmlAttribute(name = "changeset")
        protected Integer changeset;
        @XmlAttribute(name = "timestamp")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timestamp;

        @XmlAttribute(name = "user")
        protected String user;

        @XmlAttribute(name = "uid")
        protected Integer uid;

        /**
         * Gets the value of the changeset property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getChangeset() {
            return changeset;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Gets the value of the nd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNd().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Osm.Way.Nd }
         * 
         * 
         */
        public List<Osm.XMLWay.Nd> getNd() {
            if (nd == null) {
                nd = new ArrayList<Osm.XMLWay.Nd>();
            }
            return this.nd;
        }

        /**
         * Gets the value of the tag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Osm.Way.Tag }
         * 
         * 
         */
        public List<Osm.XMLWay.Tag> getTag() {
            if (tag == null) {
                tag = new ArrayList<Osm.XMLWay.Tag>();
            }
            return this.tag;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimestamp() {
            return timestamp;
        }

        /**
         * Gets the value of the uid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUid() {
            return uid;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUser() {
            return user;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getVersion() {
            return version;
        }

        /**
         * Gets the value of the visible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisible() {
            return visible;
        }

        /**
         * Sets the value of the changeset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setChangeset(Integer value) {
            this.changeset = value;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimestamp(XMLGregorianCalendar value) {
            this.timestamp = value;
        }

        /**
         * Sets the value of the uid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUid(Integer value) {
            this.uid = value;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUser(String value) {
            this.user = value;
        }


        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setVersion(Byte value) {
            this.version = value;
        }


        /**
         * Sets the value of the visible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisible(String value) {
            this.visible = value;
        }

    }
    @XmlElement(required = true)
    protected Osm.Bounds bounds;
    protected List<Osm.XMLNode> node;
    protected List<Osm.XMLWay> way;
    @XmlAttribute(name = "version")
    protected Float version;
    @XmlAttribute(name = "generator")
    protected String generator;

    @XmlAttribute(name = "copyright")
    protected String copyright;

    @XmlAttribute(name = "attribution")
    @XmlSchemaType(name = "anyURI")
    protected String attribution;

    @XmlAttribute(name = "license")
    @XmlSchemaType(name = "anyURI")
    protected String license;

    /**
     * Gets the value of the attribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribution() {
        return attribution;
    }

    /**
     * Gets the value of the bounds property.
     * 
     * @return
     *     possible object is
     *     {@link Osm.Bounds }
     *     
     */
    public Osm.Bounds getBounds() {
        return bounds;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Gets the value of the generator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerator() {
        return generator;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicense() {
        return license;
    }

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Osm.XMLNode }
     * 
     * 
     */
    public List<Osm.XMLNode> getNode() {
        if (node == null) {
            node = new ArrayList<Osm.XMLNode>();
        }
        return this.node;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Gets the value of the way property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the way property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Osm.XMLWay }
     * 
     * 
     */
    public List<Osm.XMLWay> getWay() {
        if (way == null) {
            way = new ArrayList<Osm.XMLWay>();
        }
        return this.way;
    }

    /**
     * Sets the value of the attribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribution(String value) {
        this.attribution = value;
    }

    /**
     * Sets the value of the bounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Osm.Bounds }
     *     
     */
    public void setBounds(Osm.Bounds value) {
        this.bounds = value;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }


    /**
     * Sets the value of the generator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerator(String value) {
        this.generator = value;
    }


    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicense(String value) {
        this.license = value;
    }


    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }

}
